### ISSUE TITLE
Slider: mejoras

### ISSUE THREAD

**Issue by sfabrizio** [mauroaramirez/Practicas-Profesionalizantes#10]
Aca en el slider con la imagines.. Estaria mejor si pasa solo, cada 2s-3s se deberia cambiar de pagina solo. Estoy se podria lograr con un poco de codigo javascript

**Comment by mauroaramirez** [comment]
Se realizo la mejora correctamente. Ahora el carrusel se desliza automaticamente. Se puede configurar el tiempo de esperar antes de que cambie de diapositiva. Tambien si se pone el cursor sobre el carrusel, el mismo se detiene. Se dejo configurado para que cambie de diapositiva cada 3 segundos.
