### ISSUE TITLE
Nuestros Servicios: mejorar animacion on mouse hover

### ISSUE THREAD

**Issue by sfabrizio** [mauroaramirez/Practicas-Profesionalizantes#11]
Bueno aca cuando posicionamos el mouse en los Divs (event hover), los Div se achican. Eso se ve raro, hay varias posible soluciones para esto.,, voy a recomendar una
![image](https://github.com/mauroaramirez/Practicas-Profesionalizantes/assets/4541773/56d990ad-fc57-4d5a-92e4-d51f4bfbbd0d)

Estaria bueno si hacen algo asi:
https://www.w3schools.com/howto/howto_css_flip_card.asp

**Comment by mauroaramirez** [comment]
Ya lo tengo preparado en el código. Lo dejamos para una versión a futuro.
