### ISSUE TITLE
Nav Bar: borrar este texto

### ISSUE THREAD

**Issue by sfabrizio** [mauroaramirez/Practicas-Profesionalizantes#9]
No tiene mucho sentido tener este texto, yo suguiero que hay que removerlo:

![Capture1](https://github.com/mauroaramirez/Practicas-Profesionalizantes/assets/4541773/e7153319-beca-47cb-8d46-c5ecae3ae08c)

**Comment by mauroaramirez** [comment]
Se elimino el texto.

![image](https://github.com/mauroaramirez/Practicas-Profesionalizantes/assets/74006698/c5574916-4dba-4406-b2b4-dc71f7b17a23)

**Comment by sfabrizio** [comment]
buenisimo, gracias
